services:
  db:
    image: mysql:8.0
    container_name: mysql80
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: YOURPASSWORD
      MYSQL_DATABASE: Nutrition_Facts
    ports:
    - 3306:3306
    volumes:
    # Persistent MySQL data
    - mysql-data:/var/lib/mysql
    # Directory where MySQL can LOAD DATA INFILE
    - mysql-files:/var/lib/mysql-files
    # CSVs from host -> container mysql-files
    - ./db/csv:/var/lib/mysql-files
    # Normalization script from host -> container /tmp
    - ./db/normalize_csvs.sh:/tmp/normalize_csvs.sh

volumes:
  mysql-data:
  mysql-files:
