services:
  db:
    image: mysql:8.0
    container_name: nutrition-facts-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: Nutrition_Facts
    ports:
      - 3306:3306
    volumes:
      - nutrition-facts-mysql-data:/var/lib/mysql
      - ./mysql-logs:/var/log/mysql
      - ./db/init:/docker-entrypoint-initdb.d
      - ./db/csv:/var/lib/mysql-files
    networks:
      - nutrition-facts-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 20s
      timeout: 10s

  backend:
    build:
      context: ./backend/app
      dockerfile: Dockerfile
    image: nutrition-facts-backend
    container_name: nutrition-facts-backend
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/Nutrition_Facts?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_DATASOURCE_HIKARI_INITIALIZATION_FAIL_TIMEOUT: -1
      SPRING_LOGGING_LEVEL_COM_ZAXXER_HIKARI: DEBUG
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQLDialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
    ports:
      - "8080:8080"
    networks:
      - nutrition-facts-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      retries: 5
      start_period: 20s
      timeout: 10s

  frontend:
    build:
      context: ./src/client/app
      dockerfile: Dockerfile
    image: nutrition-facts-frontend
    container_name: nutrition-facts-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:80"
    networks:
      - nutrition-facts-network
    volumes:
    - ./frontend/src:/app/src
    - ./frontend/public:/app/public

volumes:
  nutrition-facts-mysql-data:

networks:
  nutrition-facts-network:
    driver: bridge
